CB-20918 Fix search entry is missing from resolv.conf

diff --git a/saltstack/hortonworks/salt/dhcp/etc/dhcp/dhclient-enter-hooks b/saltstack/hortonworks/salt/dhcp/etc/dhcp/dhclient-enter-hooks
--- a/saltstack/hortonworks/salt/dhcp/etc/dhcp/dhclient-enter-hooks
+++ b/saltstack/hortonworks/salt/dhcp/etc/dhcp/dhclient-enter-hooks
@@ -22,9 +22,27 @@ log() {
 }
 
 generate_resolv_conf() {
-    log "Cleaning /etc/resolv.conf"
-    echo "; generated by /etc/dhcp/dhclient-enter-hooks" > /etc/resolv.conf
-    
+    JAVA_VERSION=$(java -version 2>&1 | grep -oP 'version [^0-9]?(1\.)?\K\d+' || true)
+    if [ $JAVA_VERSION -eq 11 ]; then
+        log "Java version is 11, add domain to the resolv.conf"
+        if grep -q "^domain .*" /etc/resolv.conf
+        then
+            log "domain already exists in resolv.conf"
+        else
+            DOMAIN=$(hostname -d)
+            if [ -n "$DOMAIN" ]; then
+                log "Set domain to $DOMAIN"
+                echo domain $DOMAIN >> /etc/resolv.conf
+            else
+                log "Unable to set domain as it is empty."
+            fi
+        fi
+    fi
+}
+
+make_resolv_conf() {
+    log "Starting make_resolv_conf on interface: ${interface}"
+
     if [ -n "${SEARCH}" ]; then
         search="${SEARCH}"
     else
@@ -40,6 +58,24 @@ generate_resolv_conf() {
     fi
 
     log "Search set to: ${search}"
+
+    log "Cleaning /etc/resolv.conf"
+    echo "; generated by /etc/dhcp/dhclient-enter-hooks" > /etc/resolv.conf
+
+    [ ! -f /etc/unbound/conf.d/ ] && mkdir -p /etc/unbound/conf.d/
+
+    log "Initializing /etc/unbound/conf.d/99-default.conf"
+    echo "forward-zone:" > /etc/unbound/conf.d/99-default.conf
+    echo "  name: \".\"" >> /etc/unbound/conf.d/99-default.conf
+    for nameserver in ${new_domain_name_servers} ; do
+      echo "  forward-addr: ${nameserver}" >> /etc/unbound/conf.d/99-default.conf
+    done
+
+    echo "forward-zone:" >> /etc/unbound/conf.d/99-default.conf
+    echo "  name: \"in-addr.arpa.\"" >> /etc/unbound/conf.d/99-default.conf
+    for nameserver in ${new_domain_name_servers} ; do
+      echo "  forward-addr: ${nameserver}" >> /etc/unbound/conf.d/99-default.conf
+    done
 
     log "Generating configuration for /etc/resolv.conf"
     if [ -n "${search}" ]; then
@@ -57,45 +93,14 @@ generate_resolv_conf() {
         echo $new_host_name > /etc/hostname
         hostname -F /etc/hostname
     fi
-
-    JAVA_VERSION=$(java -version 2>&1 | grep -oP 'version [^0-9]?(1\.)?\K\d+' || true)
-    if [ $JAVA_VERSION -eq 11 ]; then
-        log "Java version is 11, add domain to the resolv.conf"
-        DOMAIN=$(hostname -d)
-        if [ -n "$DOMAIN" ]; then
-            log "Set domain to $DOMAIN"
-            echo domain $DOMAIN >> /etc/resolv.conf
-        else
-            log "Unable to set domain as it is empty."
-        fi
-    fi
-}
-
-make_resolv_conf() {
-    log "Starting make_resolv_conf on interface: ${interface}"
-
-    [ ! -f /etc/unbound/conf.d/ ] && mkdir -p /etc/unbound/conf.d/
-
-    log "Initializing /etc/unbound/conf.d/99-default.conf"
-    echo "forward-zone:" > /etc/unbound/conf.d/99-default.conf
-    echo "  name: \".\"" >> /etc/unbound/conf.d/99-default.conf
-    for nameserver in ${new_domain_name_servers} ; do
-      echo "  forward-addr: ${nameserver}" >> /etc/unbound/conf.d/99-default.conf
-    done
-
-    echo "forward-zone:" >> /etc/unbound/conf.d/99-default.conf
-    echo "  name: \"in-addr.arpa.\"" >> /etc/unbound/conf.d/99-default.conf
-    for nameserver in ${new_domain_name_servers} ; do
-      echo "  forward-addr: ${nameserver}" >> /etc/unbound/conf.d/99-default.conf
-    done
-
-    generate_resolv_conf
-
+    
     log "Restart unbound"
     log "$(ps aux | grep unbound)"
     pkill -u unbound -SIGHUP unbound
     log "Restarted unbound"
     log "$(ps aux | grep unbound)"
+
+    generate_resolv_conf
 
     return 0
 }
