RMP-10375 Set hostname from reverse DNS if possible (#203)

diff --git a/saltstack/base/salt/dhcp/etc/dhcp/dhclient-enter-hooks b/saltstack/base/salt/dhcp/etc/dhcp/dhclient-enter-hooks
--- a/saltstack/base/salt/dhcp/etc/dhcp/dhclient-enter-hooks
+++ b/saltstack/base/salt/dhcp/etc/dhcp/dhclient-enter-hooks
@@ -18,6 +18,33 @@ make_resolv_conf() {
     log "Starting make_resolv_conf on interface: ${interface}"
     [ "${interface}" != "{{ pillar['network_interface'] }}" ] && return 0
 
+    if [ -n "${SEARCH}" ]; then
+        search="${SEARCH}"
+    else
+        if [ -n "${new_domain_search}" ]; then
+            # Remove instaces of \032 (#450042)
+            search="${new_domain_search//\\032/ }"
+        elif [ -n "${new_domain_name}" ]; then
+            # Note that the DHCP 'Domain Name Option' is really just a domain
+            # name, and that this practice of using the domain name option as
+            # a search path is both nonstandard and deprecated.
+            search="${new_domain_name}"
+        fi
+    fi
+
+    IP=$(ip addr show dev ${interface} | grep  -Po 'inet \K[\d.]+')
+    REVERSE_DNS=$(host $IP)
+    if [[ $? -eq 0 ]]; then
+        log "Reverse DNS for $IP: $REVERSE_DNS"
+	    FQDN=$(echo $REVERSE_DNS | awk '{ print $5 }' | sed 's/\.$//g')
+        HOSTNAME=$(echo $FQDN | sed "s/\.${search}//g")
+	    log "Setting hostname to: $HOSTNAME"
+	    echo $HOSTNAME > /etc/hostname
+        hostname -F /etc/hostname
+    else
+        log "Failed to get reverse DNS name for $IP"
+    fi
+
     log "Cleaning /etc/resolv.conf"
     echo "; generated by /etc/dhcp/dhclient-enter-hooks" > /etc/resolv.conf
 
@@ -35,20 +62,6 @@ make_resolv_conf() {
     for nameserver in ${new_domain_name_servers} ; do
       echo "  forward-addr: ${nameserver}" >> /etc/unbound/conf.d/99-default.conf
     done
-
-    if [ -n "${SEARCH}" ]; then
-        search="${SEARCH}"
-    else
-        if [ -n "${new_domain_search}" ]; then
-            # Remove instaces of \032 (#450042)
-            search="${new_domain_search//\\032/ }"
-        elif [ -n "${new_domain_name}" ]; then
-            # Note that the DHCP 'Domain Name Option' is really just a domain
-            # name, and that this practice of using the domain name option as
-            # a search path is both nonstandard and deprecated.
-            search="${new_domain_name}"
-        fi
-    fi
 
     log "Generating configuration for /etc/resolv.conf"
     if [ -n "${search}" ]; then
